version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=data

    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend

  api:
    depends_on:
      - mysqldb
    build: ./api
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_LOCAL_PORT

    networks:
      - backend

volumes:
  db:


networks:
  backend:
