version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME

    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend

  api:
    depends_on:
      - mysqldb
    build: ./api
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_LOCAL_PORT

    networks:
      - backend

volumes:
  db:


networks:
  backend:
